project:
  type: website
  output-dir: docs

website:
  title: "Piper's Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      - href: VA_analysis.qmd
        text: Coding Walkthrough
      - href: PM_resume_updated.pdf
        text: Resume
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/pipermacke
      - icon: twitter 
        href: https://twitter.com/pipermacke


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    




