project:
  type: website
  output-dir: docs

website:
  title: "PM"
  image: cropped headshot.jpg

  search: 
    location: navbar
    type: overlay
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Writing Samples
      - text: Projects
        menu:
        - href: VA_analysis.qmd
          text: Virginia Voters Analysis
        - href: graph desription.qmd
          text: Dear Data
        - href: mappingcopy.qmd
          text: Choropleth Mapping
      - href: PiperMackeResume.pdf
        text: Resume
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/pipermacke
      - icon: twitter 
        href: https://twitter.com/pipermacke


format:
  html:
    theme: minty
    css: styles.css
    toc: true
    



