project:
  type: website
  output-dir: docs

website:
  title: "Piper's Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - researchpaper.qmd
      - newsstory.qmd
  page-footer: 
    left: "Copyright 2022" 
    right: 
      - icon: github
        href: https://github.com/pipermacke
      - icon: twitter 
        href: https://twitter.com/pipermacke


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    




