---
title: "News Story"
editor: visual
---

# Research showing possibility of male birth control pill  

### Piper Macke  

 

For the first time in history, men might get to understand what it's like being "on the pill."  

A new compound designed to sterilize male mice has shown a 99% efficacy rate over just a four-week testing period. The research is being headed by collaborators at Columbia University and has so far yielded impressive results.  

Chemist and Head of the Department for Medicinal Chemistry at the University of Minnesota, Gunda Georg, Ph.D., spoke in a media briefing last Wednesday on the study.  

"You have to be careful with this analysis - these are mice; they are not humans, but nevertheless, the effect was very, very promising," George said. 

The main challenge in developing the compound currently being tested on mice was targeting a specific protein while still maintaining healthy, viable subjects. 

One of the greatest promises the research has shown is that the mice that were given the compound for several weeks seemed to have "no side effects whatsoever," according to Georg. 

Finding a working compound to cause reversible infertility in men is still in the very early stages and won't be tested on humans until it has been cleared to do so by the Food and Drug Administration.  

In which case, the soonest a working birth control pill for males could be developed is about five years from now.  

Still, the most important indicator of its overall success depends on how willing men are to take it. 

Dr. Jesse Mills, director of the Men's Clinic at UCLA, speculates that the male birth control pill will be significantly more popular among men in committed relationships opposed to men who are not. 

He also pointed out an important discrepancy in how often men and women use the procedures already available to them.  

"Our track record as a gender for assuming birth control responsibility is not stellar. Women overwhelmingly outnumber men for going through surgical sterilization procedures even though a female tubal ligation is far more invasive than a vasectomy," Mills said.  

When a 22-year-old male university student in a committed, heterosexual relationship of several months was anonymously asked if he would take the male birth control pill, he did not hesitate to say yes. 

"My girlfriend has had a tough time with the birth control she's tried. So, if there was a good birth control pill for men, I would absolutely take it instead," the source said. 

The answer differed slightly for a 22-year-old male university student that was not in a relationship.  

"I wouldn't be opposed, but I would prefer not to. Kinda scary to think about down the line," the source said. 

MD Abdullah al Noman, graduate student at the University of Minnesota Institute for Therapeutics Discovery and Development, said that this male-to-female discrepancy occurs as a result of men not having the "trade up" between the side effects of birth control and pregnancy, unlike women.  

Being that there are, at minimum, several years before a male birth control pill would be open to use by the public, there is hope that this discrepancy could still be minimized.  

Regardless, taking the steps to develop a male birth control in the first place is optimistic for millions of women suffering from the harsh side effects of methods that already exist.  

If a working oral contraceptive for men is successfully developed, the idea that Georg quoted as "reproductive choice for all" is a real possibility. 
