---
title: "Written Portfolio"
---

Paper examining the link between political leaning and reported frequency of specific crimes in the U.S. using a World Values Survey dataset to conduct a regression analysis in Stata: 

Access it: [Politics in Crime: Examining the Link Between Political Ideology and Crime Reports](<politics_in_crime.pdf>).
---

Final paper written for Data Ethics that individually analyzes the codes of conduct at big data companies IBM, Splunk, and Databricks while proposing justifications for their variations:

Access it: [Analyzing Codes of Ethics in Big Data](<ethics_final_paper.pdf>).

---

This essay analyzes the ethics of data collected for the purpose of training machine learning algorithms alongside its usage in developing more advanced artificial intelligence models: 

Access it: [Analyzing the Ethics of Machine Learning Data](<audioset_paper.pdf>). 

--- 

A collaborative paper written by myself and classmates that observes the organizational layout of Trader Joe's, examining how the corporation has created a culture and influence that vastly differs from its competition and how that has helped shape its public perception:

Access it: ["Organizational Analysis of Trader Joe's"](<https://docs.google.com/document/d/1FydmN7Ac6h12lz5fja2o5--BydKf5OnB98IBnp3zDno/edit?usp=sharing>)


--- 

My freshman year research paper that observes how the perception of female sexuality has evolved throughout history, pulling from multiple historical journals and other research papers with similar cause:

Access it: ["Female Sexuality: 
How the Historical Perception Influences the Contemporary View"](<https://docs.google.com/document/d/1PU2isaP_yhn561FKpj-Sz8lZA7hOz0k6RszMM9OOVfQ/edit?usp=sharin>). 



